module.exports = {
  env: {browser: true, es2020: true},
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:react/jsx-runtime',
    'plugin:react-hooks/recommended',
    'turbo',
    'prettier',
  ],
  ignorePatterns: ['dist', '.eslintrc.cjs', 'node_modules'],
  parserOptions: {ecmaVersion: 'latest', sourceType: 'module'},
  settings: {react: {version: '18.2'}},
  plugins: ['react-refresh'],
  rules: {
    'react-refresh/only-export-components': ['warn', {allowConstantExport: true}],
    'react-hooks/exhaustive-deps': 'error',
    'no-var': 'error',
    'brace-style': 'error',
    'prefer-template': 'error',
    radix: 'error',
    'space-before-blocks': 'error',
    'import/prefer-default-export': 'off',
    'max-len': ['error', {code: 120, tabWidth: 2, ignoreUrls: true, ignoreStrings: true}],
    'no-console': 'error',
    indent: 'error',
    'object-curly-spacing': ['error', 'always'],
    'prefer-const': 'error',
    eqeqeq: 'error',
    'no-eval': 'error',
    'no-var': 'error',
    'array-callback-return': 'error',
    'handle-callback-err': 'error',
    'no-sync': 'error',
    'one-var': ['error', 'never'],
    'no-unused-vars': 'warn',
    'sort-imports': [
      'error',
      {
        ignoreCase: true,
        ignoreDeclarationSort: true,
        ignoreMemberSort: true,
        memberSyntaxSortOrder: ['single', 'all', 'multiple', 'none'],
        allowSeparatedGroups: true,
      },
    ],
  },
  overrides: [
    {
      files: ['**/*.test.js', '**/*.test.jsx', '**/*.test.tsx', '**/*.spec.js', '**/*.spec.jsx', '**/*.spec.tsx'],
      env: {
        jest: true,
      },
    },
  ],
};
